module.exports =
    "Todo Helper": "https://github.com/Komodo/Todo"
    "Stylish": "https://github.com/Komodo/stylish"
    "Side by Side Diff": "https://github.com/Komodo/SideBySideDiff"
    "New Source Tree": "https://github.com/HTD/NST"
    "koctags": "https://github.com/agroszer/koctags"
    "Komodin Git": "https://github.com/titoBouzout/komodo-komodin-git"
    "SQLite Manager": "https://github.com/lazierthanthou/sqlite-manager"
    "Quick Diff": "https://github.com/tuomassalo/komodo-quickdiff"
    "SciViews-R": "https://github.com/cran/svKomodo"
