module.exports =
    "Monocai": "https://github.com/bdryanovski/komodoTheme"
    "Twilight": "https://github.com/igstan/komodo-themes"
    "Loco": "https://github.com/mihawk90/Loco-theme"
    "FreshCut": "https://github.com/Defman21/freshcut-komodo"
    "Spacegray": "https://github.com/Defman21/spacegray-komodo"
    "Monokai": "https://github.com/Defman21/monokai-komodo"
    "Brightgray": "https://github.com/Defman21/brightgray-komodo"
    "Spolsky": "https://github.com/Defman21/spolsky-komodo"
